module.exports = {
  Johor: [
    "Batu Bahat",
    "Johor Bahru",
    "Kluang",
    "Kota Tinggi",
    "Kulai",
    "Mersing",
    "Muar",
    "Pontian",
    "Segamat",
    "Tangkak",
  ],
  Kedah: [
    "Baling",
    "Bandar Baharu",
    "Kota Setar",
    "Kuala Muda",
    "Kubang Pasu",
    "Kulim",
    "Padang Terap",
    "Pendang",
    "Pokok Sena",
    "Sik",
    "Yan",
  ],
  Kelantan: [
    "Bachok",
    "Gua Musang",
    "Jeli",
    "Kota Bharu",
    "Kuala Krai",
    "Lojing",
    "Machang",
    "Pasir Mas",
    "Pasir Puteh",
    "Tanah Merah",
  ],
  "Kuala Lumpur": ["Kuala Lumpur"],
  Labuan: ["Labuan"],
  Melaka: ["Alor Gajah", "Jasin", "Melaka Tengah"],
  "Negeri Sembilan": [
    "Jelebu",
    "Jempol",
    "Kuala Pilah",
    "Port Dickson",
    "Rembau",
    "Seremban",
    "Tampin",
  ],
  Pahang: [
    "Bentong",
    "Bera",
    "Cameron Highlands",
    "Jerantut",
    "Kuala Lipis",
    "Kuantan",
    "Maran",
    "Pekan",
    "Raub",
    "Rompin",
    "Temerloh",
  ],
  Perak: [
    "Bagan Datuk",
    "Batang Padang",
    "Hilir Perak",
    "Hulu Perak",
    "Kampar",
    "Kerian",
    "Kinta",
    "Kuala Kangsar",
    "Larut/Matang/Selama",
    "Manjung",
    "Muallim",
    "Perak Tengah",
  ],
  Putrajaya: ["Putrajaya"],
  Perlis: ["Kuala Perlis"],
  Selangor: [
    "Banting",
    "Gombak",
    "Hulu Langat",
    "Petaling",
    "Sepang",
    "Hulu Selangor",
    "Klang",
    "Kuala Langat",
    "Kuala Selangor",
    "Pandan Indah",
    "Sabak Bernam",
    "Shah Alam",
  ],
  Terengganu: [
    "Besut",
    "Dungun",
    "Hulu Terengganu",
    "Kemaman",
    "Kuala Nerus",
    "Marang",
    "Setiu",
  ],
};
